name: try_auth
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  camera: ^0.11.1
  convex_bottom_bar: ^3.2.0
  local_auth: ^2.3.0
  mobile_scanner: ^6.0.6
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  firebase_auth: ^5.5.1
  google_sign_in: ^6.3.0
  cloud_firestore: ^5.6.5
  geolocator: ^13.0.3
  device_info_plus: ^11.3.0
  latlong2: ^0.9.1
  location: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
